#!/usr/bin/env python3
"""Verify the structure and numerical consistency of a daxpy HDF5 output file."""

import argparse
import math
import sys
from pathlib import Path

import h5py
import numpy as np


REQUIRED_ATTRIBUTES = (
    "n",
    "chunk_size",
    "number_of_chunks",
    "a",
    "x",
    "y",
    "total_sum",
    "max_abs_diff_vs_original",
)


def fail(message: str) -> None:
    raise AssertionError(message)


def check_output(filename: Path) -> None:
    if not filename.is_file():
        fail(f"File not found: {filename}")

    with h5py.File(filename, "r") as h5file:
        print(f"Inspecting: {filename}")
        print("HDF5 structure:")
        print(f"  /d                  shape={h5file['/d'].shape}, dtype={h5file['/d'].dtype}")
        print(
            "  /partial_chunk_sum "
            f"shape={h5file['/partial_chunk_sum'].shape}, "
            f"dtype={h5file['/partial_chunk_sum'].dtype}"
        )

        missing = [name for name in REQUIRED_ATTRIBUTES if name not in h5file.attrs]
        if missing:
            fail(f"Missing root attributes: {', '.join(missing)}")

        dataset_names = set(h5file.keys())
        expected_names = {"d", "partial_chunk_sum"}
        if dataset_names != expected_names:
            fail(f"Unexpected root objects: {sorted(dataset_names)}")

        n = int(h5file.attrs["n"])
        chunk_size = int(h5file.attrs["chunk_size"])
        number_of_chunks = int(h5file.attrs["number_of_chunks"])
        scalar_a = float(h5file.attrs["a"])
        scalar_x = float(h5file.attrs["x"])
        scalar_y = float(h5file.attrs["y"])

        if n <= 0 or chunk_size <= 0:
            fail(f"Invalid n={n} or chunk_size={chunk_size}")

        expected_chunks = math.ceil(n / chunk_size)
        if number_of_chunks != expected_chunks:
            fail(
                f"number_of_chunks={number_of_chunks}, "
                f"expected {expected_chunks}"
            )

        d_dataset = h5file["/d"]
        partial_dataset = h5file["/partial_chunk_sum"]

        if d_dataset.shape != (n,):
            fail(f"/d has shape {d_dataset.shape}, expected {(n,)}")
        if partial_dataset.shape != (number_of_chunks,):
            fail(
                "/partial_chunk_sum has shape "
                f"{partial_dataset.shape}, expected {(number_of_chunks,)}"
            )

        expected_hdf5_chunk = min(chunk_size, n)
        if d_dataset.chunks != (expected_hdf5_chunk,):
            fail(
                f"/d has HDF5 chunks {d_dataset.chunks}, "
                f"expected {(expected_hdf5_chunk,)}"
            )
        if d_dataset.compression != "gzip" or d_dataset.compression_opts != 4:
            fail(
                "/d compression is "
                f"{d_dataset.compression!r} level {d_dataset.compression_opts!r}, "
                "expected gzip level 4"
            )

        d_values = d_dataset[:]
        partial_values = partial_dataset[:]
        expected_value = scalar_a * scalar_x + scalar_y
        max_deviation = float(np.max(np.abs(d_values - expected_value)))

        if not np.allclose(d_values, expected_value, rtol=0.0, atol=1e-12):
            fail(f"/d values differ from a*x+y; max deviation={max_deviation:.3e}")

        recomputed_partial = np.array(
            [np.sum(d_values[start : min(start + chunk_size, n)])
             for start in range(0, n, chunk_size)]
        )
        if not np.allclose(partial_values, recomputed_partial, rtol=1e-12, atol=1e-12):
            fail("/partial_chunk_sum values do not match sums of the /d chunks")

        total_sum = float(h5file.attrs["total_sum"])
        computed_total = float(np.sum(partial_values))
        if not math.isclose(total_sum, computed_total, rel_tol=1e-12, abs_tol=1e-3):
            fail(
                f"total_sum={total_sum:.17g} does not match "
                f"sum(partial_chunk_sum)={computed_total:.17g}"
            )

        stored_max_deviation = float(h5file.attrs["max_abs_diff_vs_original"])
        if not math.isclose(stored_max_deviation, max_deviation, rel_tol=0.0, abs_tol=1e-15):
            fail(
                "max_abs_diff_vs_original="
                f"{stored_max_deviation:.3e} does not match "
                f"the computed value {max_deviation:.3e}"
            )

        print("Attributes:")
        for name in REQUIRED_ATTRIBUTES:
            print(f"  {name} = {h5file.attrs[name]}")
        print("Verification passed: structure and stored values are consistent.")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify the HDF5 file generated by daxpy_chunked."
    )
    parser.add_argument(
        "filename",
        nargs="?",
        default="output.h5",
        help="HDF5 file to inspect (default: output.h5)",
    )
    args = parser.parse_args()

    try:
        check_output(Path(args.filename))
    except (AssertionError, OSError, KeyError, ValueError) as error:
        print(f"Verification failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
